name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ./.gradle
            ./buildSrc/build
            ./build
          key: ${{ runner.os }}
      - name: Build with Gradle
        run: ./gradlew --stacktrace build
      - name: stop daemon
        run: ./gradlew --stop
